services:

  nginx:
    image: nginx:1.23.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/certfolder/fullchain.pem:/etc/nginx/jafti-certs/cert.pem
      - /etc/letsencrypt/live/certfolder/privkey.pem:/etc/nginx/jafti-certs/key.pem
    restart: always
    ports:
      - "80:80"
      - "443:443"
